apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qbvd8wyix-go 
  janus-idp.io/tekton: qbvd8wyix-go
  backstage.io/kubernetes-id: qbvd8wyix-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qbvd8wyix-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml